import {
  BookText,
  Bot,
  CodeIcon,
  FolderOpen,
  HomeIcon,
  ImagesIcon,
  MessagesSquare,
  NotebookTabsIcon,
  PaintBucket,
  Sparkles,
} from "lucide-react";

export const allNavItems = [
  {
    href: "/",
    title: "Home",
    description: "Welcome to my digital space.",
    icon: HomeIcon,
    type: "main",
  },
  {
    href: "/blog",
    title: "Blog",
    description: "Thoughts, tutorials, and ideas.",
    icon: BookText,
    type: "main",
  },
  {
    href: "/projects",
    title: "Projects",
    description: "A showcase of my work.",
    icon: FolderOpen,
    type: "main",
  },
  {
    href: "/about",
    title: "About",
    description: "Learn more about my journey.",
    icon: Sparkles,
    type: "main",
  },
  {
    href: "/shorts",
    title: "Shorts",
    description: "Notes and snippets of my thoughts.",
    icon: NotebookTabsIcon,
    type: "main",
  },
  {
    href: "/uses",
    title: "Uses",
    description: "A peek into my digital workspace.",
    imageSrc: "/setup-image.avif",
    icon: CodeIcon,
    type: "image",
  },
  {
    href: "/bucket",
    title: "Bucket List",
    description: "Things to do at least once in my life.",
    imageSrc:
      "https://images.unsplash.com/photo-1471922694854-ff1b63b20054?q=80&w=2072&auto=format&fit=crop",
    icon: PaintBucket,
    type: "image",
  },
  {
    href: "/guestbook",
    title: "Guest Book",
    description: "Leave a message for the future.",
    icon: MessagesSquare,
    type: "icon",
  },
  {
    href: "/archi",
    title: "Archi",
    description: "AI assistant to help you know me.",
    icon: Bot,
    type: "icon",
  },
  {
    href: "/gallery",
    title: "Gallery",
    description: "A gallery of moments and memories.",
    icon: ImagesIcon,
    type: "icon",
  },
];
